- tags: ufw
  become: true
  notify: Reload ufw
  block:
    - name: Install ufw
      apt:
        name: ufw
        state: present

    - name: Allow SSH
      ufw:
        rule: limit
        port: "{{ ssh_port | default('ssh') }}"
        proto: tcp

    - name: Deny incoming by default
      ufw:
        policy: deny
        direction: incoming

    - name: Allow outgoing by default
      ufw:
        policy: allow
        direction: outgoing

    - name: Allow outgoing by default
      ufw:
        policy: allow
        direction: outgoing
    
    - when: enable_forwarding is defined and enable_forwarding|bool == true
      block: 
        - name: Enable forwarding
          ansible.builtin.replace:
            path: /etc/default/ufw
            regexp: '^#?DEFAULT_FORWARD_POLICY.*'
            replace: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
            backup: yes
      
        - name: Enable forwarding
          ansible.builtin.replace:
            path: /etc/ufw/sysctl.conf
            regexp: '^#?net.ipv4.ip_forward.*'
            replace: 'net.ipv4.ip_forward=1'
            backup: yes

    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny

    - name: Enable ufw in systemd
      ansible.builtin.service:
        enabled: true
        state: started
        policy: deny