---
- tags: apt-update
  become: true
  block:
    - name: Install needrestart
      apt:
        name: needrestart
        state: present

    - name: Update the package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false

    - name: Upgrade a server with apt
      apt:
        upgrade: dist
      register: upgrade

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Run needrestart
      command: needrestart -r a
      when: upgrade.changed